### ISSUE TITLE
Can't create a variable with a number in the name

### ISSUE THREAD

**Issue by SiegfriedEhret** [ThomasCrvsr/arnoldc-to-js#2]
This doesn't end well:

```
IT'S SHOWTIME
HEY CHRISTMAS TREE variable1
YOU SET US UP 999
HEY CHRISTMAS TREE variable2
YOU SET US UP 555
TALK TO THE HAND A
TALK TO THE HAND B
YOU HAVE BEEN TERMINATED
```

Failing log:
```
~/d/arnoldc-to-js git:feature/testing ❯❯❯ node main.js examples/test.arnoldc

/home/siegfried/dev/arnoldc-to-js/arnoldc.js:169
        throw new Error(str);
              ^
Error: Parse error on line 2:
...ISTMAS TREE variable1YOU SET US UP 999
-----------------------^
Expecting 'SET_INITIAL_VALUE', got 'NUMBER'
    at Object.parseError (/home/siegfried/dev/arnoldc-to-js/arnoldc.js:169:15)
    at Object.parse (/home/siegfried/dev/arnoldc-to-js/arnoldc.js:234:22)
    at Object.<anonymous> (/home/siegfried/dev/arnoldc-to-js/main.js:13:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

```

This works:

```
IT'S SHOWTIME
HEY CHRISTMAS TREE variable
YOU SET US UP 999
HEY CHRISTMAS TREE variableu
YOU SET US UP 555
TALK TO THE HAND A
TALK TO THE HAND B
YOU HAVE BEEN TERMINATED
```

**Comment by ThomasCrvsr** [comment]
Thanks, it's fixed ! :)
